version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
- package-ecosystem: "npm"
    directory: "/sanity"
    schedule:
      interval: "daily"
